version: '3.7'
services:
  app:
    build: ./crypto-table
    ports:
      - "3000:3000"
    volumes:
      - ./crypto-table:/app
    restart: always
    networks:
      crypto-table-network:
        aliases:
          - crypto-table-app
  api:
    environment:
      CMC_URL: $CMC_URL
      CMC_API_KEY: $CMC_API_KEY
    build: ./api
    ports:
      - "8888:8888"
    volumes:
      - ./api:/api
    restart: always
    networks:
      crypto-table-network:
        aliases:
          - crypto-table-api
networks:
  crypto-table-network:
