version: '3.7'
services:
  postgres:
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    image: postgres:12.14-alpine
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    build: ./app
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
    restart: always
networks:
  pubsub-network:
